update_devices:
  name: Update devices
  description: Add new VeSync devices to Home Assistant

set_mist_level:
  name: Set Mist Level
  description: Set the mist output level of the humidifier
  target:
    entity:
      integration: vesync
      domain: humidifier
  fields:
    level:
      name: Level
      description: Mist level (1-9)
      required: true
      selector:
        number:
          min: 1
          max: 9
          step: 1

set_display:
  name: Set Display
  description: Turn the display on or off
  target:
    entity:
      integration: vesync
      domain: humidifier
  fields:
    display:
      name: Display
      description: Turn display on or off
      required: true
      selector:
        boolean:

set_drying_mode:
  name: Set Drying Mode
  description: Configure the drying mode settings
  target:
    entity:
      integration: vesync
      domain: humidifier
  fields:
    enabled:
      name: Enabled
      description: Enable or disable drying mode
      required: true
      selector:
        boolean:
    level:
      name: Level
      description: Drying level (1-3)
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 3
          step: 1

set_humidity_mode:
  name: Set Humidity Mode
  description: Set the humidity control mode
  target:
    entity:
      integration: vesync
      domain: humidifier
  fields:
    mode:
      name: Mode
      description: Operating mode (auto, manual, sleep)
      required: true
      selector:
        select:
          options:
            - auto
            - manual
            - sleep

set_target_humidity:
  name: Set Target Humidity
  description: Set the target humidity level
  target:
    entity:
      integration: vesync
      domain: humidifier
  fields:
    humidity:
      name: Humidity
      description: Target humidity level (30-80)
      required: true
      selector:
        number:
          min: 30
          max: 80
          step: 1
